TRIB-97
savvato-software/tribe-app-backend pull request #65
Opened 2023-04-26 00:21 UTC by codemechanica

2023-04-26 03:48 UTC, haxwell requested changes
See this doc: https://projectlombok.org/api/lombok/extern/slf4j/Slf4j. See if you can figure it out.. the goal is to not have a variable for the logger (the log).

2023-04-26 09:23 UTC, codemechanica commented
I’ll work on this tonight

2023-04-28 00:38 UTC, codemechanica commented
logger annotation added and all logger variable name changed to log

2023-05-01 22:32 UTC, haxwell approved these changes

2023-05-01 22:32 UTC, merged