Trib 137
savvato-software/tribe-app-backend pull request #88
Opened 2023-07-26 01:59 UTC by loretdemolas

2023-07-27 18:09 UTC, haxwell requested changes

2023-07-27 18:10 UTC, haxwell commented
Also, there are conflicts. Can you resolve those? Let me know if you need some advice.

2023-07-27 18:14 UTC, haxwell commented on src/test/java/com/savvato/tribeapp/services/NotificationServiceImplTest.java
> +		NotificationType mockType = new NotificationType();
Use an actual NotificationType instance, like NotificationType.MEDIUM_PRIORITY, or whatever's defined.

2023-07-28 00:08 UTC, loretdemolas commented on src/main/java/com/savvato/tribeapp/services/NotificationServiceImpl.java
> +    //tested
done.

2023-08-01 18:19 UTC, haxwell commented on src/test/java/com/savvato/tribeapp/services/NotificationServiceImplTest.java
> +		NotificationType mockType = new NotificationType();
It looks like you went the other direction, and removed the testing of NotificationType. I believe that still needs to be included in the test, DTO, and associated objects.

2023-08-11 01:32 UTC, loretdemolas commented on src/main/java/com/savvato/tribeapp/repositories/NotificationRepository.java
> +    @Query("SELECT n FROM Notification n WHERE n.userId = :userId")
Removed and works fine

2023-08-16 02:01 UTC, merged